- hosts: local
  tasks:
        - name: show interfaces
          command: ifconfig -a
          register: interfaces

        - name: find interesting strings
          set_fact:
            packets: "{{ interfaces['stdout'] | regex_findall('RX packets:([0-9]+)') | map('int') | sum }}"

        - name: show results
          debug:
            msg: "{{ packets }}"

